spring:
  cloud: 
    stream:
      bindings:
        input-task-queue:
          destination: task-queue-topic-wyy #相当于RocketMQ中的topic需要知道消息应该发送到哪个主题
          content-type: application/json # 内容格式。这里使用 JSON
          group: task-queue-group-wyy
          consumer: 
            concurrency: 5 # 消费者 并发线程数量5个
            #max-attempts: 1
            maxAttempts: 1
        output-function-task-result:
          destination: function-task-result-topic-wyy
          content-type: application/json
      rocketmq:
        binder:
          name-server: 10.xx.xx.xx:9876
        bindings:
          input-task-queue:
            consumer:
              enable: true #是否开启消费，默认为 true。本地测试时可关闭
              broadcasting: false # 是否使用广播消费，默认为 false 使用集群消费
              orderly: true #是否开启顺序消费
              delay-level-when-next-consume: -1
          output-function-task-result:
            producer:
              group: function-task-result-group-wyy
              sync: true  #是否同步发送消息，默认为 false 异步。
              
